# -*- coding: utf-8 -*-
"""How_to_use_CircleSegmentation_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnLGRszN7hA2Y42qViOhejhotAZjtgXv

# Example Script
This script can be used as an easy way to implement the trained unet model.
To do it, you just need to download this script and run it
"""

import torch
from imutils import paths
import numpy as np

# Remove the sample_data folder from google colab
!rm -rf /content/*
!git clone https://github.com/GiaHuyPham/DeepLearning_ComputerVision.git

"""# Setup File Directory"""

import shutil
import os

os.chdir("/content/DeepLearning_ComputerVision/CircleSegmentationUS_SpeckleImage")
os.getcwd()

"""# Device Agnostic"""

device = "cuda" if torch.cuda.is_available() else "cpu"

"""# Load and Create an Instance for the UNET Model"""

MODEL_PATH = "output/model"
unet_model = torch.load(os.path.join(MODEL_PATH,"unet_model.pth"),weights_only=False)
unet_model.to(device)

"""# Implement Model on Unseen Data"""

# Predict Masks
from PIL import Image
import cv2
from torchvision import transforms
from torchvision.transforms import InterpolationMode


# Define image input shape
INPUT_IMAGE_HEIGHT = 128
INPUT_IMAGE_WIDTH = 128

# Write a transform for image
image_transform = transforms.Compose([
    # Transfrom to PILimage
    transforms.ToPILImage(),
    # Resize our image
    transforms.Resize(size=(INPUT_IMAGE_HEIGHT,INPUT_IMAGE_WIDTH)),
    # Turn image into tensor
    transforms.ToTensor()
])

mask_transform = transforms.Compose([
    # Transfrom to PILimage
    transforms.ToPILImage(),
    # Resize our image
    transforms.Resize(size=(INPUT_IMAGE_HEIGHT,INPUT_IMAGE_WIDTH),
                      interpolation=InterpolationMode.NEAREST),
    # Turn image into tensor
    transforms.ToTensor()
])

IMAGE_UNSEEN_DATASET = os.path.join("data_unseen","images_unseen")
imagePath_unseen = sorted(list(paths.list_images(IMAGE_UNSEEN_DATASET)))
pred_masks_path = "output/pred_masks"
os.makedirs(pred_masks_path)

for imgPath in imagePath_unseen:
  image_name = os.path.basename(imgPath)

  img = cv2.imread(imgPath,0)
  img = image_transform(img)
  img = img.unsqueeze(dim=1)
  img = img.to(device)

  unet_model.eval()
  with torch.inference_mode():
    mask_logits = unet_model(img).squeeze()
    pred_mask = torch.sigmoid(mask_logits)
    pred_mask = pred_mask.cpu().numpy()
    pred_mask = (pred_mask>0.5)*255
    pred_mask = pred_mask.astype(np.uint8)

  save_name = os.path.splitext(image_name)[0].replace('img_unseen', 'mask_unseen') + '.png'
  Image.fromarray(pred_mask).save(os.path.join(pred_masks_path, save_name))

  # print(f"Saved: {save_name}")

print("Done! All predicted masks saved.")

"""## Plot"""

from pyunet.helperfunctions import make_frame_viewer
predMask_path = sorted(list(paths.list_images(pred_masks_path)))
make_frame_viewer(imagePath_unseen,predMask_path,image_transform,mask_transform)

