# -*- coding: utf-8 -*-
"""helperfunctions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bpj7haCPwqstB7VnyUCEzcbFnmCyc0Nk
"""

from timeit import default_timer as timer
import torch
def print_train_time(start:float,
                     end:float,
                     device:torch.device=None):
  """
  Prints difference between start and end time
  """
  total_time = end-start
  print(f"Train time on {device}: {total_time:.3f} seconds")
  return total_time

import torch
def train_step(data_loader: torch.utils.data.DataLoader,
               model: torch.nn.Module,
               loss_fn: torch.nn.Module,
               optimizer: torch.optim.Optimizer,
               metric_fn,
               device: torch.device="cpu"):


  ### Training
  train_loss,metric_train = 0,0

  model.train()
  # Add a loop to loop through the training batches
  for batch,(X,y) in enumerate(data_loader):
    # Put data on target device
    X,y = X.to(device),y.to(device)

    # Forward
    y_train_logits = model(X)
    # Loss
    loss = loss_fn(y_train_logits,y)
    train_loss += loss.item() # accumulate the train loss
    metric_train += metric_fn(y,torch.sigmoid(y_train_logits)).item()
    # zero grad
    optimizer.zero_grad()
    # Backprob
    loss.backward()
    # Grad. descent
    optimizer.step()

  # Calculate the average training loss of the batches
  train_loss /= len(data_loader)
  metric_train /= len(data_loader)
  # print(f"Train loss: {train_loss:.3f} | Train Metric: {metric_train:.3f}")

  return train_loss,metric_train

def test_step(data_loader: torch.utils.data.DataLoader,
              model: torch.nn.Module,
              loss_fn: torch.nn.Module,
              metric_fn,
              device: torch.device="cpu"):
  ### Testing
  test_loss,metric_test = 0,0
  model.eval()
  with torch.inference_mode():
    for X_test,y_test in data_loader:
      # Put on device
      X_test,y_test = X_test.to(device),y_test.to(device)
      # Forward
      y_test_logits = model(X_test)
      y_test_preds = torch.sigmoid(y_test_logits)
      # Calculate the loss and acc
      loss = loss_fn(y_test_logits,y_test)
      metric = metric_fn(y_test,y_test_preds)
      test_loss += loss.item()
      metric_test += metric.item()

  # Calculate the average test_loss and test_acc per batch
    test_loss /= len(data_loader)
    metric_test /= len(data_loader)
  # print(f"Test loss: {test_loss:.3f} | Test acc: {acc_test:.3f}")

  return test_loss,metric_test

def accuracy_fn(y_true, y_pred):
    """Calculates accuracy between truth labels and predictions.

    Args:
        y_true (torch.Tensor): Truth labels for predictions.
        y_pred (torch.Tensor): Predictions to be compared to predictions.

    Returns:
        [torch.float]: Accuracy value between y_true and y_pred, e.g. 78.45
    """
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct / len(y_pred)) * 100
    return acc

# Plot loss curves of a model
import matplotlib.pyplot as plt

def plot_loss_curves(results):
    """Plots training curves of a results dictionary.

    Args:
        results (dict): dictionary containing list of values, e.g.
            {"train_loss": [...],
             "train_acc": [...],
             "test_loss": [...],
             "test_acc": [...]}
    """
    loss = results["train_loss"]
    test_loss = results["test_loss"]

    accuracy = results["train_acc"]
    test_accuracy = results["test_acc"]

    epochs = range(len(results["train_loss"]))

    plt.figure(figsize=(15, 7))

    # Plot loss
    plt.subplot(1, 2, 1)
    plt.plot(epochs, loss, label="train_loss")
    plt.plot(epochs, test_loss, label="test_loss")
    plt.title("Loss")
    plt.xlabel("Epochs")
    plt.legend()

    # Plot accuracy
    plt.subplot(1, 2, 2)
    plt.plot(epochs, accuracy, label="train_accuracy")
    plt.plot(epochs, test_accuracy, label="test_accuracy")
    plt.title("Accuracy")
    plt.xlabel("Epochs")
    plt.legend()

def dice_score(mask, img_pred, threshold=0.5):

    img_pred = (img_pred > threshold).float()

    intersection = (img_pred * mask).sum(dim=(1,2,3))
    union = img_pred.sum(dim=(1,2,3)) + mask.sum(dim=(1,2,3))

    dice = (2 * intersection) / (union + 1e-8)

    return dice.mean()

import cv2
import ipywidgets as widgets
def make_frame_viewer(imagePath, maskPath, transform):
    def show_frame(iiframe):
        img = cv2.imread(imagePath[iiframe], cv2.IMREAD_GRAYSCALE)
        mask = cv2.imread(maskPath[iiframe], cv2.IMREAD_GRAYSCALE)
        img = transform(img)
        mask = transform(mask)
        plt.imshow(img.squeeze(), cmap='gray')
        plt.imshow(mask.squeeze(), cmap='Blues', alpha=0.2)
        plt.title(f"Frame {iiframe}")
        plt.show()

    return widgets.interact(
        show_frame,
        iiframe=widgets.IntSlider(
            value=0,
            min=0,
            max=len(imagePath) - 1,
            step=1,
            description='Frame:',
            continuous_update=True
        )
    )

import cv2
import matplotlib.pyplot as plt
import numpy as np
import torch
import os

def prepare_plot(origImage, origMask, predMask):
    figure, ax = plt.subplots(nrows=1, ncols=3, figsize=(10, 10))
    ax[0].imshow(origImage,cmap='gray')
    ax[1].imshow(origMask,cmap='gray')
    ax[2].imshow(predMask,cmap='gray')
    ax[0].set_title("Image")
    ax[1].set_title("Original Mask")
    ax[2].set_title("Predicted Mask")
    figure.tight_layout()
    figure.show()


def make_predictions(model, imagePath, MASK_DATASET_PATH, INPUT_IMAGE_HEIGHT, INPUT_IMAGE_WIDTH, THRESHOLD, DEVICE):
    model.eval()
    with torch.no_grad():
        image = cv2.imread(imagePath, cv2.IMREAD_GRAYSCALE)
        image = image.astype("float32") / 255.0
        image = cv2.resize(image, (INPUT_IMAGE_WIDTH, INPUT_IMAGE_HEIGHT))  # cv2 takes (W, H)
        orig = image.copy()

        filename = imagePath.split(os.path.sep)[-1]
        maskFilename = filename.replace("img", "mask")
        groundTruthPath = os.path.join(MASK_DATASET_PATH, maskFilename)

        # --- Diagnostic: check mask path and content ---
        # print(f"Mask path: {groundTruthPath}")
        # print(f"Mask file exists: {os.path.exists(groundTruthPath)}")

        gtMask = cv2.imread(groundTruthPath, 0)
        # print(f"gtMask unique values: {np.unique(gtMask)}")  # should NOT be all zeros
        gtMask = cv2.resize(gtMask, (INPUT_IMAGE_WIDTH, INPUT_IMAGE_HEIGHT))  # cv2 takes (W, H)

        image = np.expand_dims(image, 0)
        image = np.expand_dims(image, 0)
        image = torch.from_numpy(image).to(DEVICE)

        predMask = model(image).squeeze()
        # print(f"predMask raw min/max: {predMask.min():.4f} / {predMask.max():.4f}")  # check model output range
        predMask = torch.sigmoid(predMask)
        # print(f"predMask after sigmoid min/max: {predMask.min():.4f} / {predMask.max():.4f}")  # should have values > THRESHOLD
        predMask = predMask.cpu().numpy()
        predMask = (predMask > THRESHOLD) * 255
        predMask = predMask.astype(np.uint8)
        # print(f"predMask unique values: {np.unique(predMask)}")  # should contain 255 if any predictions passed threshold

        prepare_plot(orig, gtMask, predMask)