# -*- coding: utf-8 -*-
"""helperfunctions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bpj7haCPwqstB7VnyUCEzcbFnmCyc0Nk
"""

from timeit import default_timer as timer
import torch
def print_train_time(start:float,
                     end:float,
                     device:torch.device=None):
  """
  Prints difference between start and end time
  """
  total_time = end-start
  print(f"Train time on {device}: {total_time:.3f} seconds")
  return total_time

import torch
def train_step(data_loader: torch.utils.data.DataLoader,
               model: torch.nn.Module,
               loss_fn: torch.nn.Module,
               optimizer: torch.optim.Optimizer,
               accuracy_fn,
               device: torch.device="cpu"):


  ### Training
  train_loss,acc_train = 0,0

  model.train()
  # Add a loop to loop through the training batches
  for batch,(X,y) in enumerate(data_loader):
    # Put data on target device
    X,y = X.to(device),y.to(device)

    # Forward
    y_train_logits = model(X)
    # Loss
    loss = loss_fn(y_train_logits,y)
    train_loss += loss # accumulate the train loss
    acc_train += accuracy_fn(y,torch.argmax(torch.softmax(y_train_logits,dim=1),dim=1))
    # zero grad
    optimizer.zero_grad()
    # Backprob
    loss.backward()
    # Grad. descent
    optimizer.step()

  # Calculate the average training loss of the batches
  train_loss /= len(data_loader)
  acc_train /= len(data_loader)
  print(f"Train loss: {train_loss:.3f} | Train acc: {acc_train:.3f}")

def test_step(data_loader: torch.utils.data.DataLoader,
              model: torch.nn.Module,
              loss_fn: torch.nn.Module,
              accuracy_fn,
              device: torch.device="cpu"):
  ### Testing
  test_loss,acc_test = 0,0
  model.eval()
  with torch.inference_mode():
    for X_test,y_test in data_loader:
      # Put on device
      X_test,y_test = X_test.to(device),y_test.to(device)
      # Forward
      y_test_logits = model(X_test)
      y_test_preds = torch.argmax(torch.softmax(y_test_logits,dim=1),dim=1)
      # Calculate the loss and acc
      loss = loss_fn(y_test_logits,y_test)
      acc = accuracy_fn(y_test,y_test_preds)
      test_loss += loss
      acc_test += acc

  # Calculate the average test_loss and test_acc per batch
    test_loss /= len(data_loader)
    acc_test /= len(data_loader)
    print(f"Test loss: {test_loss:.3f} | Test acc: {acc_test:.3f}")

def accuracy_fn(y_true, y_pred):
    """Calculates accuracy between truth labels and predictions.

    Args:
        y_true (torch.Tensor): Truth labels for predictions.
        y_pred (torch.Tensor): Predictions to be compared to predictions.

    Returns:
        [torch.float]: Accuracy value between y_true and y_pred, e.g. 78.45
    """
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct / len(y_pred)) * 100
    return acc

# Plot loss curves of a model
def plot_loss_curves(results):
    """Plots training curves of a results dictionary.

    Args:
        results (dict): dictionary containing list of values, e.g.
            {"train_loss": [...],
             "train_acc": [...],
             "test_loss": [...],
             "test_acc": [...]}
    """
    loss = results["train_loss"]
    test_loss = results["test_loss"]

    accuracy = results["train_acc"]
    test_accuracy = results["test_acc"]

    epochs = range(len(results["train_loss"]))

    plt.figure(figsize=(15, 7))

    # Plot loss
    plt.subplot(1, 2, 1)
    plt.plot(epochs, loss, label="train_loss")
    plt.plot(epochs, test_loss, label="test_loss")
    plt.title("Loss")
    plt.xlabel("Epochs")
    plt.legend()

    # Plot accuracy
    plt.subplot(1, 2, 2)
    plt.plot(epochs, accuracy, label="train_accuracy")
    plt.plot(epochs, test_accuracy, label="test_accuracy")
    plt.title("Accuracy")
    plt.xlabel("Epochs")
    plt.legend()

def dice_score(mask,img_pred,threshold=0.5):
  img_pred = (img_pred > threshold).float()
  intersection = (img_pred * mask).sum()
  return (2*intersection)/(img_pred.sum() + mask.sum() + 1e-8)

