# -*- coding: utf-8 -*-
"""SegmentationDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfxasgVOYwRgk5xxiwKlo7y1t4TAbZ0a
"""

from torch.utils.data import Dataset
import cv2

class SegmentationDataset(Dataset): # A custom Dataset must be a subclass of torch.utils.data
  def __init__(self,imagePath:str,
               maskPath:str,
               image_transform=None,
               mask_transform=None):
    self.imagePath = imagePath
    self.maskPath = maskPath
    self.image_transform = image_transform
    self.mask_transform = mask_transform

  def __len__(self): # The __len__() method must be overide
    return len(self.imagePath)

  def __getitem__(self,idx:int): # The __getitem__() method must also be overide
    image_file = self.imagePath[idx]
    mask_file = self.maskPath[idx]

    # Read the image and mask
    img = cv2.imread(image_file,cv2.IMREAD_GRAYSCALE)
    mask = cv2.imread(mask_file,cv2.IMREAD_GRAYSCALE)

    if self.image_transform is not None:
      img = self.image_transform(img)

    if self.mask_transform is not None:
      mask = self.mask_transform(mask)
      mask = (mask>0.5).float()

    return img,mask

