# -*- coding: utf-8 -*-
"""Unet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4EaMIT5Xx7H4SLK2lgKA0SE6NMkpMSv
"""

import torch
from torch import nn
from torch.nn import Module
from torch.nn import ModuleList
from torchvision.transforms import CenterCrop
from torch.nn import functional as F

"""The Block class corresponds to one convolutional layer/ level of the unet"""
class Block(Module):
  def __init__(self,inChannels,outChannels): # The input and output channels depend on which level we are at.
                                             # For example, for the level, the input channel is 1 (for grayscale) and
                                             # the output channels are 16 (depending on how many feature maps we want to have)
    super().__init__()
    self.block = nn.Sequential(
        nn.Conv2d(in_channels=inChannels,out_channels=outChannels,kernel_size=3),
        nn.ReLU(),
        nn.Conv2d(in_channels=outChannels,out_channels=outChannels,kernel_size=3)
    )

  def forward(self,x):
    return self.block(x)

"""The Encoder class summarize the whole downsampling process of the unet"""
class Encoder(Module):
  def __init__(self, channels=(1,16,32,64)): # The variable channels contains the input and output shapes/channels for each layer and level
     super().__init__()
     self.encBlocks = ModuleList(
         [Block(channels[i],channels[i+1]) for i in range(len(channels)-1)]
     ) # Each loop corresponds to one level of the unet
     self.maxPool = nn.MaxPool2d(kernel_size=2)

  def forward(self,x):
    # Initialize empty variable to store the output of each block, which will be use later by the decoder/upsampling
    blockOutputs = []
    # Passing through each block layer
    for block in self.encBlocks: # Loop through each layer
      x = block(x) # -> Output of a encoder layer
      blockOutputs.append(x) # Append the outputs of each layer
      x = self.maxPool(x)

    return blockOutputs

class Decoder(Module):
  def __init__(self,channels=(64,32,16)):
    super().__init__()
    self.channels = channels
    self.upconv = ModuleList(
        [nn.ConvTranspose2d(in_channels=channels[i],out_channels=channels[i+1],kernel_size=2,stride=2) for i in range(len(channels)-1)]
    )
    self.decBlocks = ModuleList(
        [Block(channels[i],channels[i+1]) for i in range(len(channels)-1)]
    )

  def forward(self,x,encFeatures):
    # Loop through the decoder layer
    for i in range(len(self.channels)-1):
      # Pass through the upsampling block
      x = self.upconv[i](x)
      # Crop the feature maps output from the encoder to match the upsampled feature maps to match the same-level
      encFeats = self.crop(encFeatures[i],x)
      # Concatenate the both feature maps from enc and dec
      x = torch.cat([x,encFeats],dim=1)
      # Pass through the decBlocks
      x = self.decBlocks[i](x)

      return x

  def crop(self,encFeatures,x):
    (_,_,H,W) = x.shape
    encFeatures = CenterCrop([H,W])(encFeatures)
    return encFeatures

class Unet(Module):
  def __init__(self,encChannels=(1,16,32,64),
               decChannels=(64,32,16),
               numClass=1,
               retainDim=True,
               outputSize=(128,128)):
    super().__init__()
    self.encoder = Encoder(encChannels)
    self.decoder = Decoder(decChannels)

    self.output_layer = nn.Conv2d(in_channels=decChannels[-1],
                          out_channels=numClass,
                          kernel_size=1) # This is the output layer, which convert the last 16 feature maps of the decoder into segmented regions
    self.retainDim = retainDim
    self.outputSize = outputSize

  def forward(self,x):
    # Pass through the encoder
    encFeatures = self.encoder(x)

    # Pass through the decoder
    decFeatures = self.decoder(encFeatures[::-1][0], # Taks the last feature maps output of the encoder as input for the decoder
                               encFeatures[::-1][1:] # The remaining skip-connections, i.e. the higher feature maps output of the encoder used for combing with the upsampled value
                               )

    # Pass through the output layer
    img_seg = self.output_layer(decFeatures)

    # Check if the dimension of the output is retained, if true -> resize
    if self.retainDim:
      img_seg = F.interpolate(img_seg,self.outputSize)

    return img_seg